# Mysql数据库
spring:
  datasource:
    ## 默认是hirari
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT&nullCatalogMeansCurrent=true
    username: root
    password: 123456

    # 连接池大小根据实际情况调整
    max-active: 100
    max-pool-prepared-statement-per-connection-size: 100

logging:
  config: classpath:logback-dev.xml

redis:
  host: localhost
  port: 6379
  db: 0
  pool:
    max-active: 200
    max-wait: 10000
    max-idle: 100
    min-idle: 5
